2020-01-04T15:55:00.5378859+01:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2020-01-04T15:55:00.5578870+01:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2020-01-04T15:55:00.5658875+01:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-01-04T15:55:00.5718878+01:00  [INF] Hosting environment: "Development" (c3307c92)
2020-01-04T15:55:00.5808883+01:00  [INF] Content root path: "G:\AttendanceControl.API\AttendanceControl.API" (b5d60022)
2020-01-04T15:55:13.1706084+01:00 0HLSH4OCH1NAJ:00000001 [INF] Request starting HTTP/1.1 PUT https://localhost:5001/api/absences/80 application/json 4 (ca22a1cb)
2020-01-04T15:55:13.4166225+01:00 0HLSH4OCH1NAJ:00000001 [INF] Executing endpoint '"AttendanceControl.API.Controllers.AbsenceController.SetExcused (AttendanceControl.API)"' (500cc934)
2020-01-04T15:55:13.9456527+01:00 0HLSH4OCH1NAJ:00000001 [INF] Route matched with "{action = \"SetExcused\", controller = \"Absence\"}". Executing controller action with signature "System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] SetExcused(Int32, Boolean)" on controller "AttendanceControl.API.Controllers.AbsenceController" ("AttendanceControl.API"). (122b2fdf)
2020-01-04T15:55:19.2649570+01:00 0HLSH4OCH1NAJ:00000001 [WRN] The 'bool' property '"IsCurrent"' on entity type '"SchoolClassEntity"' is configured with a database-generated default. This default will always be used for inserts when the property has the value 'false', since this is the CLR default for the 'bool' type. Consider using the nullable 'bool?' type instead so that the default will only be used for inserts when the property value is 'null'. (a2a8ca4b)
2020-01-04T15:55:19.4229660+01:00 0HLSH4OCH1NAJ:00000001 [INF] Entity Framework Core "3.1.0" initialized '"AttendanceControlDBContext"' using provider '"Pomelo.EntityFrameworkCore.MySql"' with options: "None" (9958f5bb)
2020-01-04T15:55:21.8061023+01:00 0HLSH4OCH1NAJ:00000001 [ERR] An error occurred using the connection to database '"attendance_control"' on server '"localhost"'. (5fc3407c)
2020-01-04T15:55:23.2901872+01:00 0HLSH4OCH1NAJ:00000001 [ERR] An exception occurred while iterating over the results of a query for context type '"AttendanceControl.API.DataAccess.AttendanceControlDBContext"'."
""System.InvalidOperationException: An exception has been raised that is likely due to a transient failure. Consider enabling transient error resiliency by adding 'EnableRetryOnFailure()' to the 'UseMySql' call.
 ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Authentication method 'caching_sha2_password' failed. Either use a secure connection, specify the server's RSA public key with ServerRSAPublicKeyFile, or set AllowPublicKeyRetrieval=True.
   at MySqlConnector.Core.ServerSession.GetRsaPublicKeyAsync(String switchRequestName, ConnectionSettings cs, IOBehavior ioBehavior, CancellationToken cancellationToken)
   at MySqlConnector.Core.ServerSession.SwitchAuthenticationAsync(ConnectionSettings cs, PayloadData payload, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs:line 573
   at MySqlConnector.Core.ServerSession.ConnectAsync(ConnectionSettings cs, ILoadBalancer loadBalancer, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs:line 431
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ConnectionPool.cs:line 112
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ConnectionPool.cs:line 141
   at MySql.Data.MySqlClient.MySqlConnection.CreateSessionAsync(ConnectionPool pool, Nullable`1 ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 645
   at MySql.Data.MySqlClient.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 312
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlRelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()" (f5c7ac34)
System.InvalidOperationException: An exception has been raised that is likely due to a transient failure. Consider enabling transient error resiliency by adding 'EnableRetryOnFailure()' to the 'UseMySql' call.
 ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Authentication method 'caching_sha2_password' failed. Either use a secure connection, specify the server's RSA public key with ServerRSAPublicKeyFile, or set AllowPublicKeyRetrieval=True.
   at MySqlConnector.Core.ServerSession.GetRsaPublicKeyAsync(String switchRequestName, ConnectionSettings cs, IOBehavior ioBehavior, CancellationToken cancellationToken)
   at MySqlConnector.Core.ServerSession.SwitchAuthenticationAsync(ConnectionSettings cs, PayloadData payload, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs:line 573
   at MySqlConnector.Core.ServerSession.ConnectAsync(ConnectionSettings cs, ILoadBalancer loadBalancer, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs:line 431
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ConnectionPool.cs:line 112
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ConnectionPool.cs:line 141
   at MySql.Data.MySqlClient.MySqlConnection.CreateSessionAsync(ConnectionPool pool, Nullable`1 ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 645
   at MySql.Data.MySqlClient.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 312
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlRelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
2020-01-04T15:55:24.6862671+01:00 0HLSH4OCH1NAJ:00000001 [INF] Executed action "AttendanceControl.API.Controllers.AbsenceController.SetExcused (AttendanceControl.API)" in 10666.1877ms (afa2e885)
2020-01-04T15:55:24.7082683+01:00 0HLSH4OCH1NAJ:00000001 [INF] Executed endpoint '"AttendanceControl.API.Controllers.AbsenceController.SetExcused (AttendanceControl.API)"' (99874f2b)
2020-01-04T15:55:25.0222863+01:00 0HLSH4OCH1NAJ:00000001 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.InvalidOperationException: An exception has been raised that is likely due to a transient failure. Consider enabling transient error resiliency by adding 'EnableRetryOnFailure()' to the 'UseMySql' call.
 ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Authentication method 'caching_sha2_password' failed. Either use a secure connection, specify the server's RSA public key with ServerRSAPublicKeyFile, or set AllowPublicKeyRetrieval=True.
   at MySqlConnector.Core.ServerSession.GetRsaPublicKeyAsync(String switchRequestName, ConnectionSettings cs, IOBehavior ioBehavior, CancellationToken cancellationToken)
   at MySqlConnector.Core.ServerSession.SwitchAuthenticationAsync(ConnectionSettings cs, PayloadData payload, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs:line 573
   at MySqlConnector.Core.ServerSession.ConnectAsync(ConnectionSettings cs, ILoadBalancer loadBalancer, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs:line 431
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ConnectionPool.cs:line 112
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ConnectionPool.cs:line 141
   at MySql.Data.MySqlClient.MySqlConnection.CreateSessionAsync(ConnectionPool pool, Nullable`1 ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 645
   at MySql.Data.MySqlClient.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 312
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlRelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at AttendanceControl.API.DataAccess.Repositories.AbsenceRepository.Get(Int32 absenceId) in G:\AttendanceControl.API\AttendanceControl.API.DataAccess\Repositories\AbsenceRepository.cs:line 35
   at AttendanceControl.API.Application.Services.AbsenceService.SetExcused(Int32 absenceId, Boolean isExcused) in G:\AttendanceControl.API\AttendanceControl.API.Application\Services\AbsenceService.cs:line 58
   at AttendanceControl.API.Controllers.AbsenceController.SetExcused(Int32 absenceId, Boolean isExcused) in G:\AttendanceControl.API\AttendanceControl.API\Controllers\AbsenceController.cs:line 44
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
2020-01-04T15:55:25.1512937+01:00 0HLSH4OCH1NAJ:00000001 [INF] Executing endpoint '"AttendanceControl.API.Controllers.ErrorController.Error (AttendanceControl.API)"' (500cc934)
2020-01-04T15:55:25.1872957+01:00 0HLSH4OCH1NAJ:00000001 [INF] Route matched with "{action = \"Error\", controller = \"Error\"}". Executing controller action with signature "Microsoft.AspNetCore.Mvc.IActionResult Error()" on controller "AttendanceControl.API.Controllers.ErrorController" ("AttendanceControl.API"). (122b2fdf)
2020-01-04T15:55:25.2352985+01:00 0HLSH4OCH1NAJ:00000001 [INF] Executing ObjectResult, writing value of type '"AttendanceControl.API.Errors.ApiError"'. (8a1b66c8)
2020-01-04T15:55:25.4363100+01:00 0HLSH4OCH1NAJ:00000001 [INF] Executed action "AttendanceControl.API.Controllers.ErrorController.Error (AttendanceControl.API)" in 136.3463ms (afa2e885)
2020-01-04T15:55:25.4523109+01:00 0HLSH4OCH1NAJ:00000001 [INF] Executed endpoint '"AttendanceControl.API.Controllers.ErrorController.Error (AttendanceControl.API)"' (99874f2b)
2020-01-04T15:55:25.5033138+01:00 0HLSH4OCH1NAJ:00000001 [INF] Request finished in 12340.6316ms 500 application/json; charset=utf-8 (791a596a)
2020-01-04T15:56:13.2670457+01:00 0HLSH4OCH1NAJ:00000002 [INF] Request starting HTTP/1.1 PUT https://localhost:5001/api/absences/80 application/json 4 (ca22a1cb)
2020-01-04T15:56:13.2770463+01:00 0HLSH4OCH1NAJ:00000002 [INF] Executing endpoint '"AttendanceControl.API.Controllers.AbsenceController.SetExcused (AttendanceControl.API)"' (500cc934)
2020-01-04T15:56:13.2830466+01:00 0HLSH4OCH1NAJ:00000002 [INF] Route matched with "{action = \"SetExcused\", controller = \"Absence\"}". Executing controller action with signature "System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] SetExcused(Int32, Boolean)" on controller "AttendanceControl.API.Controllers.AbsenceController" ("AttendanceControl.API"). (122b2fdf)
2020-01-04T15:56:13.4580567+01:00 0HLSH4OCH1NAJ:00000002 [INF] Entity Framework Core "3.1.0" initialized '"AttendanceControlDBContext"' using provider '"Pomelo.EntityFrameworkCore.MySql"' with options: "None" (9958f5bb)
2020-01-04T15:56:13.9800865+01:00 0HLSH4OCH1NAJ:00000002 [INF] Executed DbCommand ("353"ms) [Parameters=["@__absenceId_0='?' (DbType = Int32)"], CommandType='Text', CommandTimeout='30']"
""SELECT `a`.`id`, `a`.`date`, `a`.`is_excused`, `a`.`school_class_id`, `a`.`student_id`, `a`.`type`
FROM `absence` AS `a`
WHERE `a`.`id` = @__absenceId_0
LIMIT 1" (0723d8ff)
2020-01-04T15:56:15.0481476+01:00 0HLSH4OCH1NAJ:00000002 [INF] Executed action "AttendanceControl.API.Controllers.AbsenceController.SetExcused (AttendanceControl.API)" in 1754.7444ms (afa2e885)
2020-01-04T15:56:15.0541479+01:00 0HLSH4OCH1NAJ:00000002 [INF] Executed endpoint '"AttendanceControl.API.Controllers.AbsenceController.SetExcused (AttendanceControl.API)"' (99874f2b)
2020-01-04T15:56:15.0801494+01:00 0HLSH4OCH1NAJ:00000002 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
AttendanceControl.API.Business.Exceptions.DataNotFoundException: No se ha encontrado la ausencia, el id no existe
   at AttendanceControl.API.DataAccess.Repositories.AbsenceRepository.Get(Int32 absenceId) in G:\AttendanceControl.API\AttendanceControl.API.DataAccess\Repositories\AbsenceRepository.cs:line 42
   at AttendanceControl.API.Application.Services.AbsenceService.SetExcused(Int32 absenceId, Boolean isExcused) in G:\AttendanceControl.API\AttendanceControl.API.Application\Services\AbsenceService.cs:line 58
   at AttendanceControl.API.Controllers.AbsenceController.SetExcused(Int32 absenceId, Boolean isExcused) in G:\AttendanceControl.API\AttendanceControl.API\Controllers\AbsenceController.cs:line 44
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
2020-01-04T15:56:15.0941502+01:00 0HLSH4OCH1NAJ:00000002 [INF] Executing endpoint '"AttendanceControl.API.Controllers.ErrorController.Error (AttendanceControl.API)"' (500cc934)
2020-01-04T15:56:15.1071510+01:00 0HLSH4OCH1NAJ:00000002 [INF] Route matched with "{action = \"Error\", controller = \"Error\"}". Executing controller action with signature "Microsoft.AspNetCore.Mvc.IActionResult Error()" on controller "AttendanceControl.API.Controllers.ErrorController" ("AttendanceControl.API"). (122b2fdf)
2020-01-04T15:56:15.1151514+01:00 0HLSH4OCH1NAJ:00000002 [INF] Executing ObjectResult, writing value of type '"AttendanceControl.API.Errors.ApiError"'. (8a1b66c8)
2020-01-04T15:56:15.1401529+01:00 0HLSH4OCH1NAJ:00000002 [INF] Executed action "AttendanceControl.API.Controllers.ErrorController.Error (AttendanceControl.API)" in 9.0764ms (afa2e885)
2020-01-04T15:56:15.1581539+01:00 0HLSH4OCH1NAJ:00000002 [INF] Executed endpoint '"AttendanceControl.API.Controllers.ErrorController.Error (AttendanceControl.API)"' (99874f2b)
2020-01-04T15:56:15.1991562+01:00 0HLSH4OCH1NAJ:00000002 [INF] Request finished in 1925.0662ms 404 application/json; charset=utf-8 (791a596a)
2020-01-04T15:59:16.8205444+01:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2020-01-04T15:59:16.8375454+01:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2020-01-04T15:59:16.8435457+01:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-01-04T15:59:16.8475459+01:00  [INF] Hosting environment: "Development" (c3307c92)
2020-01-04T15:59:16.8535463+01:00  [INF] Content root path: "G:\AttendanceControl.API\AttendanceControl.API" (b5d60022)
2020-01-04T15:59:22.2878571+01:00 0HLSH4QN7QUMF:00000001 [INF] Request starting HTTP/1.1 PUT https://localhost:5001/api/absences/80 application/json 4 (ca22a1cb)
2020-01-04T15:59:22.3998635+01:00 0HLSH4QN7QUMF:00000001 [INF] Executing endpoint '"AttendanceControl.API.Controllers.AbsenceController.SetExcused (AttendanceControl.API)"' (500cc934)
2020-01-04T15:59:22.6838798+01:00 0HLSH4QN7QUMF:00000001 [INF] Route matched with "{action = \"SetExcused\", controller = \"Absence\"}". Executing controller action with signature "System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] SetExcused(Int32, Boolean)" on controller "AttendanceControl.API.Controllers.AbsenceController" ("AttendanceControl.API"). (122b2fdf)
2020-01-04T15:59:26.6561070+01:00 0HLSH4QN7QUMF:00000001 [WRN] The 'bool' property '"IsCurrent"' on entity type '"SchoolClassEntity"' is configured with a database-generated default. This default will always be used for inserts when the property has the value 'false', since this is the CLR default for the 'bool' type. Consider using the nullable 'bool?' type instead so that the default will only be used for inserts when the property value is 'null'. (a2a8ca4b)
2020-01-04T15:59:26.7901146+01:00 0HLSH4QN7QUMF:00000001 [INF] Entity Framework Core "3.1.0" initialized '"AttendanceControlDBContext"' using provider '"Pomelo.EntityFrameworkCore.MySql"' with options: "None" (9958f5bb)
2020-01-04T15:59:28.1851944+01:00 0HLSH4QN7QUMF:00000001 [INF] Executed DbCommand ("199"ms) [Parameters=["@__absenceId_0='?' (DbType = Int32)"], CommandType='Text', CommandTimeout='30']"
""SELECT `a`.`id`, `a`.`date`, `a`.`is_excused`, `a`.`school_class_id`, `a`.`student_id`, `a`.`type`
FROM `absence` AS `a`
WHERE `a`.`id` = @__absenceId_0
LIMIT 1" (0723d8ff)
2020-01-04T15:59:29.2212537+01:00 0HLSH4QN7QUMF:00000001 [INF] Executed action "AttendanceControl.API.Controllers.AbsenceController.SetExcused (AttendanceControl.API)" in 6508.996300000001ms (afa2e885)
2020-01-04T15:59:29.2332544+01:00 0HLSH4QN7QUMF:00000001 [INF] Executed endpoint '"AttendanceControl.API.Controllers.AbsenceController.SetExcused (AttendanceControl.API)"' (99874f2b)
2020-01-04T15:59:29.4882689+01:00 0HLSH4QN7QUMF:00000001 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
AttendanceControl.API.Business.Exceptions.DataNotFoundException: No se ha encontrado la ausencia, el id no existe
   at AttendanceControl.API.DataAccess.Repositories.AbsenceRepository.Get(Int32 absenceId) in G:\AttendanceControl.API\AttendanceControl.API.DataAccess\Repositories\AbsenceRepository.cs:line 42
   at AttendanceControl.API.Application.Services.AbsenceService.SetExcused(Int32 absenceId, Boolean isExcused) in G:\AttendanceControl.API\AttendanceControl.API.Application\Services\AbsenceService.cs:line 58
   at AttendanceControl.API.Controllers.AbsenceController.SetExcused(Int32 absenceId, Boolean isExcused) in G:\AttendanceControl.API\AttendanceControl.API\Controllers\AbsenceController.cs:line 44
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
2020-01-04T15:59:29.5262711+01:00 0HLSH4QN7QUMF:00000001 [INF] Executing endpoint '"AttendanceControl.API.Controllers.ErrorController.Error (AttendanceControl.API)"' (500cc934)
2020-01-04T15:59:29.5902748+01:00 0HLSH4QN7QUMF:00000001 [INF] Route matched with "{action = \"Error\", controller = \"Error\"}". Executing controller action with signature "Microsoft.AspNetCore.Mvc.IActionResult Error()" on controller "AttendanceControl.API.Controllers.ErrorController" ("AttendanceControl.API"). (122b2fdf)
2020-01-04T15:59:29.6172763+01:00 0HLSH4QN7QUMF:00000001 [INF] Executing ObjectResult, writing value of type '"AttendanceControl.API.Errors.ApiError"'. (8a1b66c8)
2020-01-04T15:59:29.6732795+01:00 0HLSH4QN7QUMF:00000001 [INF] Executed action "AttendanceControl.API.Controllers.ErrorController.Error (AttendanceControl.API)" in 71.64240000000001ms (afa2e885)
2020-01-04T15:59:29.6862803+01:00 0HLSH4QN7QUMF:00000001 [INF] Executed endpoint '"AttendanceControl.API.Controllers.ErrorController.Error (AttendanceControl.API)"' (99874f2b)
2020-01-04T15:59:29.9442950+01:00 0HLSH4QN7QUMF:00000001 [INF] Request finished in 7460.8073ms 404 application/json; charset=utf-8 (791a596a)
